name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v[0-9]+.*

env:
  GITHUB_PAT: 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
  RUST_BACKTRACE: 1

permissions:
  contents: write

jobs:
  test:
    name: Windows-x86_64 with rust ${{ matrix.toolchain }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: dod_miner.exe
            name: dod_miner-windows-x86_64.zip
        toolchain:
          - stable
          #          - beta
          #           - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Configure Git
        run: |
          git config --global user.email "dod_miner@dod.cool"
          git config --global user.name "dod"
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: 'build'
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: '--release --package=dod_miner'
          strip: true
      - name: Package as archive
        if: startsWith( github.ref, 'refs/tags/v' )
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          cd -
      - name: Publish release artifacts
        if: startsWith( github.ref, 'refs/tags/v' )
        uses: actions/upload-artifact@v3
        with:
          name: dod_miner-${{ matrix.platform.os_name }}
          path: 'dod_miner-*'
      - name: Generate SHA-256
        if: matrix.platform.os == 'windows-latest' && startsWith( github.ref, 'refs/tags/v' )
        run: shasum -a 256 ${{ matrix.platform.name }}
      - name: Publish GitHub release
        if: startsWith( github.ref, 'refs/tags/v' )
        uses: softprops/action-gh-release@v1
        with:
          files: 'dod_miner-*'
          token: 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
