name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: push


env:
  RUST_BACKTRACE: 1

permissions:
  contents: write

jobs:
  test:
    name: Windows-x86_64 with rust ${{ matrix.toolchain }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: dod_miner.exe
            name: dod_miner-windows-x86_64.zip
        toolchain:
          - stable
          #          - beta
          #           - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Configure Git
        run: |
          git config --global user.email "dod_miner@dod.cool"
          git config --global user.name "dod"
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: 'build'
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: '--release --package=dod_miner'
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
